"""60 — T0.7 ROLE CENSUS + T0.8 ALREADY-SHIPPED CENSUS (research charter WS0).

Pure grep-and-read work, no data pulls. Two jobs:

  T0.7  Enumerate every site that computes or consumes a role concept
        (team_role / role_lead / role_pct / role_env_ok / role_alpha_ok, plus
        role_priors.py's carry-share prior), say what each means, and mark which
        derive from `total_points` (and are therefore NOT independent evidence).
        Then state how role_lead's MAGNITUDE (_ROLE_LEAD_K) would have to be
        reconstructed if an ordinal depth-chart pos_rank replaced team_role.

  T0.8  For every hypothesis in charter section 8 (H1, H2a-g, H3a-e, H4-*,
        H5a-f, F1-F6), grep the repo for the quantity it proposes and record in
        one line what already computes it (S13: grep before you propose), then
        list the hypotheses at risk of a FALSE NULL because the board already
        prices their signal.

The grep evidence is printed live (PART 1/3) so the results file carries its own
receipts; the curated tables cite those file:line numbers. A small pandas block
re-verifies the charter's apply_bonuses numbers on players_final.csv ([V]).

Run:  .venv/bin/python icm/work/mc_research/60_censuses.py
Writes: icm/work/mc_research/results_60_censuses.txt
"""
import os
import re
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(HERE, "results_60_censuses.txt")

lines = []


def say(s=""):
    print(s)
    lines.append(s)


def grep(rel_path, pattern, label=None):
    """Print line-numbered matches of `pattern` in repo file `rel_path`. Returns match count."""
    path = os.path.join(ROOT, rel_path)
    say(f"  $ grep -nE '{pattern}' {rel_path}" + (f"   # {label}" if label else ""))
    if not os.path.exists(path):
        say("    (FILE MISSING)")
        return 0
    rx = re.compile(pattern)
    n = 0
    with open(path, encoding="utf-8") as f:
        for i, ln in enumerate(f, 1):
            if rx.search(ln):
                n += 1
                say(f"    {i}:{ln.rstrip()[:150]}")
    if n == 0:
        say("    (no matches)")
    return n


ROLE_RX = r"team_role|role_lead|role_pct|role_env_ok|role_alpha_ok|_ROLE_LEAD_K"

say("=" * 100)
say("60 — T0.7 ROLE CENSUS + T0.8 ALREADY-SHIPPED CENSUS   (generated by 60_censuses.py, no data pulls)")
say("Charter: icm/work/research-blueprint-prompt.md sections T0.7, T0.8, S13, 2.4-2.6.")
say("Labels: [V] = executed now by this script; [R] = read from a prior results file / code comment.")
say("=" * 100)

# ----------------------------------------------------------------------------------------------
say()
say("PART 1 — RAW GREP EVIDENCE: the five role tokens across the six named files + test suites [V]")
say("-" * 100)
counts = {}
for f in ("advisor.py", "value_board.py", "app_pages/draft.py", "tools/preflight.py",
          "cohort_priors.py", "role_priors.py"):
    counts[f] = grep(f, ROLE_RX)
    say()
say("  test suites:")
for f in ("tests/test_role_alpha.py", "tests/test_handcuff.py", "tests/test_cohort_skew.py"):
    counts[f] = grep(f, ROLE_RX)
    say()
say(f"  matching-line counts [V]: " + ", ".join(f"{k}={v}" for k, v in counts.items()))
say("  (charter 2.4/T0.7 said advisor 16 / value_board 12 / draft 6 / preflight 3 / cohort_priors 1"
    " plus three test suites — counts above are today's ground truth; role_priors.py contains none of"
    " the five tokens because its role concept is a carry-share PRIOR, see R10 below.)")

# ----------------------------------------------------------------------------------------------
say()
say("=" * 100)
say("PART 2 — T0.7 ROLE CENSUS (curated; every file:line cited is printed in PART 1)")
say("-" * 100)
say("""
COMPUTE SITES
R1  value_board.py:41-43   team_role = position + rank of `total_points` within (team, position)
    ("BUF WR1"). Means: the teammate our blended projection likes most — NOT a depth chart.
    DERIVED FROM total_points -> not independent evidence (charter 2.6 calls this out).
R2  value_board.py:48-51   role_lead = own total_points minus the best OTHER teammate at the position,
    in projected season POINTS (+25 = clear alpha, ~0 = coin-flip room, negative = behind the alpha).
    DERIVED FROM total_points. This is the only role object that carries a MAGNITUDE.
R3  value_board.py:57-61   role_env_ok = team above-median in team_implied_total (hand-typed Vegas) OR
    in 2025 measured skill-player targets. INDEPENDENT of total_points (market + measured usage).
R4  value_board.py:89-93   role_pct = xppg percentile within position (ff_opportunity xFP), falling
    back to best-of-2024/25 target-share percentile, then 0.5. Base branch INDEPENDENT of
    total_points (measured opportunity).
R5  value_board.py:98-112  ...BUT role_pct is OVERRIDDEN by the VOLS percentile for switched-team
    players (85 of 536) and "ascending" same-team leads (gate: role_lead >= 15 & vols_pct >=
    role_pct + 0.25). For that population role_pct IS total_points-derived — the 0.09 role weight
    becomes a second helping of VOLS (charter 2.6: "competes with nothing" population).
R6  value_board.py:118-123 W_R 0.09 x rank(role_pct) enters rank_composite.
R7  value_board.py:169     team_role / role_lead / role_env_ok written to value_board.csv — the
    contract the app, advisor, preflight and cohort layers read.
R8  app_pages/draft.py:90-94  FALLBACK recompute of team_role from total_points for an older board
    CSV — a byte-for-byte duplicate of R1's formula living in a second file. DERIVED FROM
    total_points. This is a SIXTH role site the charter's five-site count does not name: any swap of
    the role definition that misses it lets an old CSV silently resurrect the projection-derived role.
R9  app_pages/draft.py:104-115  role_alpha_ok = best-DEMONSTRATED target share (max 2024/25) >= top
    same-team RB/TE share − 0.03 (L34 Mike-Evans-behind-CMC gate). INDEPENDENT (measured shares).
R10 role_priors.py (whole file) -> role_data.csv `share_2025` = previous-season measured carry share
    per stint. INDEPENDENT — the repo's ONLY measured, non-projection role prior. Contains none of
    the five tokens but is a role concept by its own header; consumed via advisor._roles() (97-109)
    by _go_score (500-514), the handcuff read (551), and the DART profiles (609-632).

CONSUME SITES
R11 advisor.py:364-365     _ROLE_LEAD_K = 0.5 (VONA per POINT of role_lead), _ROLE_CAP = 10.0.
R12 advisor.py:368-385     _role_bonus_series: nudge = clip(role_lead x 0.5, +/-10), RB/WR/TE only,
    zeroed unless role_env_ok; WR positive nudge stripped unless role_alpha_ok. Inherits the
    total_points derivation through role_lead.
R13 advisor.py:1465        pool["_rk"] = vona + _role_bonus_series(pool) — the ONE place role moves a
    rank (TOP PICKS ordering). Everything else is display/prose.
R14 advisor.py:554         handcuff line displays the backup's team_role (prose only).
R15 advisor.py:1327,1393   team_role in the advisor shortlist table, renamed "role" (LLM display).
R16 advisor.py:1573-1581   shortlist tags: "CLEAR ALPHA" iff role_lead >= 15 & env_ok & alpha_ok;
    "behind the alpha" iff role_lead <= -15. Thresholds denominated in projected POINTS.
R17 tools/preflight.py:44,48-49  team_role / role_lead / role_env_ok are REQUIRED columns and
    (team_role, role_env_ok) are NO-NaN columns — a role-schema change breaks preflight first.
R18 cohort_priors.py:85    role_rank = the digits of team_role -> a kNN MATCHING FEATURE baked into
    cohort_data.csv. DERIVED (transitively) from total_points — cohort odds partially match on the
    projection's own room ordering.
R19 tests/test_role_alpha.py (pins R12's nudge semantics: cap, env gate, alpha strip, backward
    compat); tests/test_handcuff.py:43-44 (team_role in the board fixture); tests/test_cohort_skew.py:
    69-78 (role_lead / team_role / role_env_ok fixture columns).

DERIVATION SUMMARY
  Derived from total_points (NOT independent evidence): R1, R2, R5 (its override population),
  R8, R18 — and consumers R12/R13/R16 inherit it through role_lead.
  Independent evidence: R3 (Vegas + measured targets), R4's base branch (xFP / target share),
  R9 (measured target shares), R10 (measured carry share).
  So of the role family, exactly FOUR signals contain information the projection does not already
  contain — and the one that moves a rank with MAGNITUDE (role_lead via R13) is not one of them.
""")

say("-" * 100)
say("T0.7 REQUIRED PARAGRAPH — reconstructing role_lead's MAGNITUDE if ordinal pos_rank replaces team_role")
say("-" * 100)
say("""
role_lead is denominated in projected season points, and every consumer constant is calibrated in
that currency: _ROLE_LEAD_K converts it at 0.5 VONA per point capped at +/-10 (advisor.py:364-365, so
the nudge saturates at |role_lead| = 20 points), the CLEAR-ALPHA / behind-the-alpha prose fires at
+/-15 points (advisor.py:1580-1581), and value_board's ascend gate re-bases role_pct at role_lead >=
15 (value_board.py:111). A real depth-chart `pos_rank` (load_depth_charts 2025/2026 schema) is
ORDINAL — it says WR1 vs WR2 but never "leads by 25" vs "leads by 2" — so a naive swap deletes the
exact quantity all three constants consume: a coin-flip WR1 (Burden +2) and a landslide WR1 (DJ Moore
+25) become indistinguishable, which is precisely the failure gap-scaling was built to avoid
(advisor.py:359-363 comment). Reconstruction options, none free, each a research object with its own
validation burden: (a) HYBRID — take ORDER from pos_rank, keep magnitude as the projection gap
between the depth-chart-ordered players; requires a defined semantic for disagreements, because when
the chart and the projection disagree the chart's No.1 carries a NEGATIVE projected lead; (b) FIT a
magnitude map from ordinal slots — e.g. the historical distribution of realized usage/points gaps by
depth slot and position — a new fitted constant that needs its own out-of-sample check before it may
feed _ROLE_LEAD_K; (c) RE-FIT the consumer constants in a new currency (binary alpha flag or rank
gap), which means simultaneously re-deriving _ROLE_LEAD_K, _ROLE_CAP, both +/-15 thresholds and the
ascend gate. Whichever option is chosen, the change touches five production files plus three test
suites AT ONCE, and R8's silent fallback duplicate of the team_role formula in app_pages/draft.py:
90-94 must be changed in the same pass or an older CSV resurrects the projection-derived role. This
is L52/L53's recorded failure mode at larger scale — the snake-pick schedule lived in four places and
was wrong in three; "a partial fix to a duplicated concept is worse than no fix." Role lives in six.
""")

# ----------------------------------------------------------------------------------------------
say("=" * 100)
say("PART 3 — RAW GREP EVIDENCE FOR T0.8: the charter's named already-shipped instances [V]")
say("-" * 100)
grep("apply_bonuses.py", r"def blended|sack_rate|L_sack|sr = |\* sr \*|r_rush100|fd_carry|fd_rec|K\s*=\s*max",
     "per-player EB long-TD rates + per-QB sack rate + league-average tier/FD rates")
say()
grep("scoring_config.py", r"^K = ", "EB shrinkage constant (charter: K=12)")
say()
grep("advisor.py", r"def _go_score|def _survival_prob|_SCALE_ADP = |_SCALE_S = |def _handcuff_read|pos != \"RB\"|def _pos_punt_loss|HEALTH FLAGS",
     "_go_score, survival curve, RB-only handcuff gate, punt read, health-fact line")
say()
grep("compute_outcomes.py", r"def draft_tilt|proven = |tilt \* 0.86|new_hc|base scoring only",
     "draft-capital tilt, Wave-2b proven/unproven mover split, new-HC tilt, base-scoring weekly proxy")
say()
grep("value_board.py", r"^W_V, W_E|ceil_val = |floor_val = |repl_pts\[pos\]",
     "distributional composite (W_UP 0.25 / W_DN 0.15) + board-side replacement points")
say()
grep("compute_metrics.py", r"replacement_level", "replacement level from total_points (bonus-inclusive)")
say()
grep("utils.py", r"FIXED_STARTERS|def startable_counts", "QB12/K12 fixed replacement (C12 boundary)")
say()
grep("load_ff_opportunity.py", r"total_fantasy_points_exp|xppg|regression",
     "standard-scoring xFP -> xppg / xppg_diff / regression (shipped TD-luck lens)")
say()
grep("projections.py", r"proj_divergence", "proj_divergence computed here, then merged + written, read nowhere")
say()
grep("app_pages/draft.py", r"def injury_map|injury_status|injury_sev",
     "live Sleeper health-FACT merge into the board (F6 largely exists)")
say()
grep("tools/injury_watch.py", r"IS usable in preseason|PUP", "preseason PUP prevalence already measured Jul 27")
say()
grep("icm/work/mc_research/01_build_panel.py", r"wk\[\"pts\"\] = |passing_yards\"\]\*0\.04|receptions\"\]\*1",
     "research panel scores BASE PPR only, hardcoded weights, no bonuses/sacks/FDs (S12 gap)")
say()
grep("icm/work/mc_research/44_survival_curve_backtest.py", r"_SD_ADP|_SD = ",
     "a SECOND measured dispersion table (opponent pick-sd) distinct from advisor._SCALE_S")

# ----------------------------------------------------------------------------------------------
say()
say("PART 4 — [V] PANDAS RE-VERIFICATION of the charter's apply_bonuses numbers (players_final.csv)")
say("-" * 100)
df = pd.read_csv(os.path.join(ROOT, "players_final.csv"))
top12 = df.sort_values("total_points", ascending=False).groupby("position").head(12)
mb = top12.groupby("position")["bonus_points"].mean().round(1)
say(f"  mean bonus_points, top-12 by total_points [V]: RB {mb.get('RB')}, WR {mb.get('WR')}, "
    f"TE {mb.get('TE')}, QB {mb.get('QB')}   (charter: RB +64.2 / WR +34.9 / TE +24.8 / QB -8.9)")
qb12 = df[df.position == "QB"].nlargest(12, "total_points")
rb12 = df[df.position == "RB"].nlargest(12, "total_points")
say(f"  top-12 QB bonus span [V]: {qb12.bonus_points.max() - qb12.bonus_points.min():.1f}  (charter: 35.0)")
say(f"  top-12 RB bonus span [V]: {rb12.bonus_points.max() - rb12.bonus_points.min():.1f} "
    f"({rb12.bonus_points.min():.1f} -> {rb12.bonus_points.max():.1f})  (charter: 13.5, 57.2 -> 70.7)")
q = df[df.position == "QB"].copy()
q["raw_rank"] = q["custom_proj_points"].rank(ascending=False)
q["tot_rank"] = q["total_points"].rank(ascending=False)
maye = q[q.full_name.str.contains("Maye")].iloc[0]
say(f"  Drake Maye [V]: custom_proj {maye.custom_proj_points:.1f} (raw rank {maye.raw_rank:.0f}), "
    f"bonus {maye.bonus_points:.1f}, total {maye.total_points:.1f} (rank {maye.tot_rank:.0f})")
say("  DISCREPANCY vs charter: charter says Maye is 2nd on custom_proj_points; today's file ranks him"
    " 3rd (Lamar Jackson 371.8 > Maye 370.7). The material claim holds (-25.9 sack tax, 10th on"
    " total_points, a 7-spot re-rank) but the charter's '2nd / eight-spot' wording drifted by one.")

# ----------------------------------------------------------------------------------------------
say()
say("=" * 100)
say("PART 5 — T0.8 ALREADY-SHIPPED CENSUS: one line per charter-section-8 hypothesis")
say("(what already computes the proposed quantity; 'NOTHING' = grepped, zero live sites)")
say("-" * 100)
say("""
CHARTER'S OWN LIST, VERIFIED [V this session, file:line printed in PART 3]:
  * Per-QB sack rate      apply_bonuses.py:36-41 (EB shrink toward L_sack, K=12 scoring_config.py:42),
                          applied :82 + :98 (m["pass_att"] * sr * SACK). Numbers re-verified PART 4.
  * Long-TD EB rates      apply_bonuses.py:20-28 (blended(), K=12), applied :79-81 + :89-91.
  * _go_score             advisor.py:500-514 (share_2025>=.30 / implied>=23 / pos price<=50), consumed
                          :550 (handcuff) and :671 (dart); carry share from role_data.csv (R10).
  * draft_tilt            compute_outcomes.py:50 (def), applied :163 (rookies only).
  * Wave-2b mover split   compute_outcomes.py:173-180 (proven = wk_mean>=10 & games>=12; unproven
                          changer tilt x0.86, sigma x1.20).
  * 44_ survival backtest icm/work/mc_research/results_44_survival_backtest.txt: pooled n=2000 mean
                          -3.0, 95% CI [-5.1, -0.9], 80.5% identical [R].
  * Distributional board  value_board.py:11 (W_UP .25 / W_DN .15), :79-80 (ceiling_healthy /
                          floor_healthy minus repl_pts), :118-123 (40% of the composite).

HYPOTHESIS-BY-HYPOTHESIS:
H1    Variance decomposition: NOTHING computes it. Nearest shipped: Wave-2 changer tilts
      (compute_outcomes.py:165-180) + switched_team staleness override (value_board.py:98-101,
      load_ff_opportunity.py:67-79). Research panel is base-PPR only (01_build_panel.py) — T0.3 gap.
H2a   Personnel-mix carryover: NOTHING computes personnel rates (load_participation / load_ftn_charting:
      zero live call sites). Adjacent shipped: new-HC stayer tilt (compute_outcomes.py:137-143,194) +
      playcaller PROSE line (advisor.py:120-124, 212, 1724-1727; price adjustment explicitly forbidden).
H2b   Touch-concentration (HHI) carryover: NOTHING (grep hhi/herfindahl: zero). Nearest: role_priors.py
      share_2025 — player-level, not caller-level.
H2c   Goal-line / inside-5 tendency: NOTHING in the live chain (grep yardline/inside-5: zero;
      apply_bonuses reads pbp only for TD length / FG / sack / 2pt / PAT).
H2d   Contract intent: load_contracts / guaranteed money used NOWHERE. The stated baseline already
      ships: _go_score + role_data.csv carry share; rookie capital already priced by draft_tilt (C4).
H2e   OL continuity: NOTHING computes it. The object it perturbs — per-QB sack rate pooled 2023-25 —
      ships at apply_bonuses.py:36-41; H2e is a STALENESS question about a shipped feature.
H2f   Adjectival camp text: NOTHING (correct — charter deletes it). Factual health layer: LARGELY
      SHIPS — see M1 below. Prevalence already measured: 4 PUP + 15 Q in top-150 ADP, Jul 27
      (tools/injury_watch.py:9-13 header).
H2g   Real depth charts: NOTHING consumes load_depth_charts in the live chain (only icm research
      00_survey.py touches it). The signal it would replace/contradict is R1-R8 of PART 2.
H3a   Two-gate in-season detector: NOTHING — no in-season layer exists at all (app_pages/ = draft.py +
      setup.py [V ls]); no mechanism feed exists.
H3b   Change-point methods: NOTHING (grep cusum/changepoint: zero).
H3c   Earned-vs-vacated (participation): NOTHING (grep load_participation: zero live sites).
H3d   YPC / TD-rate blacklist: nothing to unship (no YPC trigger exists). The lens it redirects to —
      TD-luck — ALREADY ships as xppg_diff/regression (load_ff_opportunity.py:57+, board column
      `regression`, advisor renames to `regr` advisor.py:1392).
H3e   Position suppression: the TE rule is ALREADY ENFORCED IN DATA at the draft layer — _handcuff_read
      is RB-ONLY (advisor.py:522-523 docstring citing boom 4.5% p=5.5e-6; :540 `if pos != "RB"`),
      pinned by tests/test_handcuff.py. No in-season variant exists (no in-season layer).
H4-QB (collapsed into H5c by the charter) The strawman it targeted does not exist: VOLS vs
      startable_counts ships (compute_metrics.py:11-17, utils.py:58/63) + PUNT READ punt_loss
      (advisor.py:1198-1249).
H4-RB Role-forecast sub-model: baseline ships as role_data.csv carry share (role_priors.py) +
      _go_score. NOT shipped: goal-line presence, pass-snap participation, passing-down binary,
      per-player FD rate (league-average fd_carry/fd_rec only, apply_bonuses.py:60-61 + :95-96).
H4-WR Distribution model: the incumbent is 40% of the composite (value_board.py:11,118-123) + cv_rel
      bounded sigma personalization (compute_outcomes.py:136,198) + computed-but-UNUSED boom_rate/
      bust_rate/p10/p90/P_pos2/P_pos3 (compute_outcomes.py:79,146,220-224).
H4-TE Blocker-vs-catcher classification: NOTHING. snap_share_2025 is display-only (advisor.py:1376);
      the TE1/TE2 label is projection-derived (R1).
H5a   WR aDOT archetypes: no aDOT in the live chain. PARTIAL pricing ships via per-player long-rec-TD
      EB rates (apply_bonuses.py:27,80,90) + the ceiling term.
H5b   Per-player threshold rates: the league-average constants it replaces ship at apply_bonuses.py:
      55-61, applied :92-96; the per-player EB pattern ships IN THE SAME FILE (blended() :20-28,
      K=12). Charter's split (long-TD per-player, all else league-rate) verified exact.
H5c   Sack tax: SHIPS (see charter-list entry + PART 4). The three open questions (staleness /
      invisibility / shrinkage) are properties of the shipped term, not new features.
H5d   Full-bonus MC weekly scoring: the base-scoring proxy it replaces is compute_outcomes.py:62-74,
      with an in-code comment declaring the omission deliberate (protects the 62.1% OOS calibration).
H5e   League-scored xFP: NOTHING. Standard-scoring xFP ships end-to-end: load_ff_opportunity.py:43-58
      -> xppg/xppg_diff/regression -> role_pct (value_board.py:90-93) + advisor xPPG (advisor.py:1380).
H5f   League-scoring replacement level: the 2026 BOARD side already prices it — replacement_level is
      computed from bonus-inclusive total_points (apply_bonuses.py:103 -> compute_metrics.py:11-17;
      utils.py:58 FIXED_STARTERS QB12/K12; value_board.py:72-75 repl_pts). The RESEARCH PANEL does not
      (base PPR) — that gap IS the hypothesis, and it is an S12 instrument problem, not a new feature.
F1    Role replace-or-beside: the five-plus-one role sites are PART 2 of this file (R1-R19).
F2    Discarded signals: proj_divergence flows projections.py:91 -> apply_bonuses.py:76 ->
      value_board.py:169 and is READ NOWHERE downstream [V grep]; boom/bust/p10/p90/P_pos2/P_pos3
      computed + written + never surfaced (compute_outcomes.py:79,146,220-224); FantasyPros sd/best/
      worst exist NOWHERE (load_ecr.py maps TIERS -> ecr_tier, which is itself carried unused).
F3    In-season surface: NONE exists — app_pages/ holds draft.py and setup.py only [V].
F4    Reachability: _survival_prob ships (advisor.py:789-812, anchors :789-790) and drives VONA /
      wheel / punt / lookahead (charter 2.4). Ready to import as-is.
F5    ADP dispersion validation: advisor._SCALE_ADP/_SCALE_S is the single LIVE site (:789-790).
      NOTE: 44_ carries a SECOND measured dispersion table (_SD_ADP/_SD at 44_:47-48, values
      3.3->32.5) — that is the sd of (actual pick - ADP) for OPPONENT simulation, a different object
      from the survival logistic scale (1.8->17.9). Not an app bug, but exactly the two-curves trap
      T0.4 warns about: the new grader must IMPORT advisor's curve, never copy-paste 44_'s.
F6    Health fact feed: the surface ALREADY EXISTS (M1). Missing vs the charter's ask: only the
      explicit early-August PUP/NFI framing and the C16 citation in the advisor text.
""")

# ----------------------------------------------------------------------------------------------
say("=" * 100)
say("PART 6 — WHAT THE CHARTER'S OWN LIST MISSED (found by this census)")
say("-" * 100)
say("""
M1  The forward-only health FACT feed (F6 / H2f-factual) ALREADY SHIPS IN THREE PLACES:
    tools/injury_watch.py (CLI watch; header documents live Sleeper injury_status IS usable in
    preseason — 15 Questionable + 4 PUP of top-150, run Jul 27); app_pages/draft.py:147-170
    injury_map() merges live Sleeper injury_status/notes/severity into the board on every app rerun;
    advisor.py:1344-1363 renders the HEALTH FLAGS line and already says "FACTS, not forecasts".
    The charter's "The BOARD has no injury input at all" is true of value_board.csv but NOT of the
    app+advisor stack. H2f's one required prevalence measurement (S5, "does the flag ever fire")
    was effectively run on Jul 27: ~2.7% PUP in the top-150.
M2  H3e's TE suppression already exists IN DATA at the draft layer (advisor.py:540 RB-only gate,
    pinned by tests/test_handcuff.py) — encode the in-season rule by citing C14 AND this precedent.
M3  xppg_diff / `regression` is a shipped TD-luck diagnostic (load_ff_opportunity.py:57+) — it is
    both H3d's redirect target and the seed of the charter 7.13 xFP bridge object.
M4  cv_rel bounded weekly-volatility personalization ships (compute_outcomes.py:136,198, clipped
    [0.80, 1.30] — C18's surviving fragment). Any distribution-shape hypothesis (H4-WR, H5b weekly
    mode, F2) competes with this too, not only with the ceiling/floor weights.
M5  A SIXTH role site: app_pages/draft.py:90-94 duplicates value_board's team_role formula as a
    fallback. T0.7's five-site count under-counts by one; any role swap must include it.
M6  Two different measured dispersion curves exist (advisor._SCALE_S vs 44_'s _SD) — name both once
    in T0.4 or inherit an L52 (see F5 line above).
M7  Charter drift: Maye is 3rd, not 2nd, on custom_proj_points in today's players_final.csv
    (PART 4). Immaterial to H5c, but re-pin any charter [V] number before quoting it downstream.
""")

# ----------------------------------------------------------------------------------------------
say("=" * 100)
say("PART 7 — FALSE-NULL RISK (S13): hypotheses whose signal the board ALREADY PRICES")
say("A rebuilt feature graded against a board that already prices it returns a false null on a real")
say("edge, which then gets recorded as a closed line. Ranked by risk:")
say("-" * 100)
say("""
HIGH RISK
1  H2g / F1 / H4-RB (role signals). The board carries SIX role expressions including an independent
   one (role_pct's xppg/target-share branch), and W_R is only 0.09 of the composite — against an
   arm-2 that contains them, even a VALID depth-chart signal produces a structurally small delta.
   Mitigation (the charter's own): grade the 85 switched-team + ascend population separately, where
   role_pct IS the VOLS percentile (R5) and a real role signal competes with nothing.
2  H5c (sack tax). Already re-ranks the 2026 board (Maye -25.9 -> 10th). If arm 2 is reconstructed
   WITHOUT the shipped term, arm 3 merely rediscovers it (fake positive vs the wrong baseline); if
   arm 2 includes it, "add a sack term" is a no-op (false null). Only the three named deltas —
   staleness (H2e), invisibility (T0.3), shrinkage (K cross-validation) — are honest tests.
3  H5b (long-TD half). Already per-player EB-shrunk; re-deriving that half returns ~0 and would read
   as "per-player rates do not matter". Restrict the endpoint to the genuinely-league-average
   constants: first-down rates + 100/200/300/400 yardage-tier rates.
4  H2d (capital predictor). draft_tilt already prices rookie capital and C4's surviving fragment says
   capital is near-inert for players who already hold a role — exactly this population. Keep
   guaranteed money as the ONLY new axis or the test measures a shipped signal.
5  H4-WR (distribution). 40% of the composite + cv_rel + the unused MC distribution columns already
   express shape; the charter replaced the draft falsification for exactly this reason — hold to the
   replacement (aDOT-archetype vs ceiling_healthy/floor_healthy), or the null is structural.
MODERATE RISK
6  H1 (mover terms). Wave-2/2b tilts sit inside arm 2's MC mean AND sigma, so the situation MEAN is
   partially priced in-system; a decomposition run only against the reconstructed system understates
   the raw situation share. Report both raw-vs-price and vs-system decompositions.
7  H2a (full regime). The star-level effect ships as the new-HC stayer tilt (x1.02, sigma x0.85);
   only the second-order WR3/TE2 tier is genuinely unpriced. A pooled premise test dilutes to null —
   restrict the target tier before measuring carryover R^2.
8  H5f (replacement level). Not board-priced — INSTRUMENT-blind: graded on a base-PPR panel the
   allocation edge is invisible BY CONSTRUCTION (S12). A base-scored grader returns a guaranteed
   false null; T0.3 is a hard prerequisite, not an optimization.
9  F5 (survival curve). 44_ already graded the curve in points (-3.0, shipped on correctness);
   re-grading re-litigates a decided line. Only the FFC cross-check of the dispersion VALUES is open.
LOW RISK (quantity genuinely absent from the system; a null there is informative, not structural):
   H2b, H2c, H2e, H3a, H3b, H3c, H3d, H4-TE, H5a (mostly), H5d, H5e, F2's sd/best/worst half, F3, F6.
""")

say("=" * 100)
say("END. Every [V] above was executed by this script on this run; [R] items cite their results file.")
say("A future reader can reconstruct every claim from PART 1/3's greps + PART 4's pandas block.")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"\nwrote {OUT}")
